baseURL = "https://mrmarble.dev/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "vim"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Alvaro Tinoco · Landing Page"

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Alvaro Tinoco"
  email = "atinoco@protonmail.com"
  description = "Landing Page"
  bio = "Full Stack Web Developer.  \nPython Enthusiast."
  avatar = "img/avatar.png"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/MrMarble"
    linkedin = "https://www.linkedin.com/in/alvaro-tinoco-marmol/"
