zbaseURL = "https://mrmarble.github.io/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
disableRSS      = true
editor          = "vim"
enableRobotsTXT = true
language        = "en"
languageCode    = "en"
relativeURLs    = true
theme           = "vncnt-hugo"
title           = "Alvaro Tinoco"

_merge = "none"

[permalinks]
    fixed = ":title/"
    posts = "posts/:slug/"

[params]
    author      = "Alvaro Tinoco"
    avatar      = "img/avatar.png"
    bio         = "Full Stack Developer.  \nGo Enthusiast."
    description = "Business card"
    email       = "atinoco@protonmail.com"
    error404    = "There is no such page."
    favicon     = "img/favicon.ico"

    [params.contact]
        github   = "https://github.com/MrMarble"
        linkedin = "https://www.linkedin.com/in/alvaro-tinoco-marmol/"
